#==============================================================================
# Kubeadm Role - Handlers
#==============================================================================
---
- name: Reload systemd
  systemd:
    daemon_reload: yes
